### ISSUE TITLE
llrt_modules/url module depends on llrt_core/http module

### ISSUE THREAD

**Issue by ahaoboy** [awslabs/llrt#579]
When only the url module is imported, an error will be reported because there is no url module

If there are module dependencies but they are not added in order when used, can an error be reported during compilation? Otherwise, it is difficult to find the problem without checking the source code.

```rust
    fn evaluate<'js>(ctx: &Ctx<'js>, exports: &Exports<'js>) -> Result<()> {
        let globals = ctx.globals();
        let url: Constructor = globals.get(stringify!(URL))?;
        let url_search_params: Constructor = globals.get(stringify!(URLSearchParams))?;
```
1.  What is the difference between stringify!(URL) and "URL"
2. url_crate  ```url = ["url_crate"]```  seems to be a invalid feature

**Comment by nabetti1720** [comment]
If you are not getting the expected behavior with respect to the name “url”, then the fix you implemented in #560 may be missing.　I will check back later in the week.

Incidentally, for No. 2, in order to distinguish between the `url` to be obtained from crates.io and the `url` as a feature name, a different name is given as follows.

```toml
url_crate = { version = “2.5”, package = “url”, optional = true }
```

**Comment by ahaoboy** [comment]
https://github.com/ahaoboy/rquickjs-llrt-demo/blob/main/src/main.rs

Here is a minimal reproducible demo. The problem is that the url module depends on http, but there is no prompt at compile time, and an error will be reported at runtime, which is very unfriendly to developers who are not familiar with llrt.

**Comment by nabetti1720** [comment]
Thank you for presenting the reproduction procedure. I think I understand the problem.

I think it is because the URL class is not defined in the URL Module, the class definition itself is done on the http side, and the URL Module is defined to refer to the global object defined by http.

Please give me some time to think about it. :)

**Comment by nabetti1720** [comment]
Hi @ahaoboy , As a result of PR #584, it appears that URL/URLSearchParams can be independent of the http module.

**Comment by richarddavison** [comment]
Can we close this now @ahaoboy ?

**Comment by ahaoboy** [comment]
> Can we close this now @ahaoboy ?

Still need to import the url module first, but there is no other choice in the short time

https://github.com/ahaoboy/rquickjs-llrt-demo
