### ISSUE TITLE
Loading node_modules with import/require

### ISSUE THREAD

**Issue by nabetti1720** [awslabs/llrt#589]
We know that bundling is better for performance, but for experimental or less performance-intensive use cases, it would be great if node_modules loading could be supported.

```javascript
// index4.js
import { Event } from "event-target-shim";

globalThis.Event = Event

import { Bench } from 'tinybench';

const bench = new Bench({ time: 100 });

import mod from '../package.json';

bench
  .add('json', async () => {
    JSON.stringify(mod)
  })
await bench.warmup();
await bench.run();
console.log(bench.table());
```

```shell
% llrt ./src/index4.js
ReferenceError: Error resolving module 'event-target-shim' from './src/index4.js'
```

**Comment by ahaoboy** [comment]
Resolve is very complex, for reference:

https://crates.io/crates/oxc_resolver

https://www.npmjs.com/search?q=enhanced-resolve

**Comment by richarddavison** [comment]
Yes, agree that this is super useful but also very complex:
ESM: https://nodejs.org/api/esm.html#resolution-and-loading-algorithm
CJS: https://nodejs.org/api/modules.html#all-together

Maybe we should do a basic support that doesn't handle all the edge cases?

**Comment by nabetti1720** [comment]
As for import, it seems to work by creating a Custom Resolver (NpmJsResolver) and implementing a path resolution mechanism similar to require. It is starting to work on the laptop at hand. I will do some more testing and then PR.

**Comment by richarddavison** [comment]
> As for `import`, it seems to work by creating a custom resolver (NpmJsResolver) and implementing a path resolution mechanism similar to `require`.
>

We should probably converge the resolver mechanism here:: https://github.com/awslabs/llrt/blob/9ab07457df115e55ae5012c17c4db3746ba65d2f/llrt_core/src/vm.rs#L106

The name "BinaryResolver" also doesn't make sense since it does work with multiple sources (not just precompiled bytecode). With basic requite functionality now in place, I think the whole resolution implementation needs a refactoring so it's not duplicated for CJS/ESM imports.
It needs to support:

1. multiple directories to look for code and `node_modules` (defaults to current working directory and `/opt`)
2. node module resolution
3. json imports/require
4. precompiled binaries (from bytecode_cache and on filesystem)
