### ISSUE TITLE
Lambda init timeout when using SFN client

### ISSUE THREAD

**Issue by georeeve** [awslabs/llrt#694]
As soon as I add `const client = new SFNClient({});` to a lambda using LLRT, I start getting init timeouts with no other errors:
```
2024-11-19T10:34:33.325Z
INIT_START Runtime Version: provided:al2023.v41
2024-11-19T10:34:43.325Z
INIT_REPORT Init Duration: 9999.76 ms Phase: init Status: timeout
2024-11-19T10:35:43.372Z
INIT_REPORT Init Duration: 60026.37 ms Phase: invoke Status: timeout
```

Works fine:
```typescript
export const main = async () => {
    console.log('Test');
};
```

Times out:
```typescript
import { SFNClient } from '@aws-sdk/client-sfn';

const client = new SFNClient({});

export const main = async () => {
    console.log('Test');
};
```

I am using CDK LLRT with version `v0.3.0-beta`. From the README, SFN is bundled with `std-sdk` and `full-sdk`, I have tried both and get the same result. Is there a way to debug these init timeouts?

**Comment by nabetti1720** [comment]
@richarddavison, I've done a little research into the issues that have been reported.

- Looking at the AWS online documentation, it says that there are two types of endpoints: `states` and `sync-states` (excluding fips).
https://docs.aws.amazon.com/general/latest/gr/step-functions.html

- However, in the actual implementation, there are no `sync-states`.
https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-sfn/src/endpoint/ruleset.ts

How should we understand this? Is the timeout occurring because we're communicating with a non-existent endpoint?
Perhaps there's some condition that causes the `sync-` prefix to be added, but I couldn't find it...

**Comment by nabetti1720** [comment]
I have tested the above concerns and found that they are reoccurring. Please wait for the PR as it will be posted shortly. :)

Before:
```
// sdk.cfg
...
client-sfn,SFN,states,sync-states,0
...
```
```
INIT_REPORT Init Duration: 10009.31 ms	Phase: init	Status: timeout
INIT_REPORT Init Duration: 60060.34 ms	Phase: invoke	Status: timeout
START RequestId: abfbc9a5-bd31-46a1-afac-90c11ac4390c Version: $LATEST
2024-11-19T13:17:02.379Z abfbc9a5-bd31-46a1-afac-90c11ac4390c Task timed out after 60.06 seconds

END RequestId: abfbc9a5-bd31-46a1-afac-90c11ac4390c
REPORT RequestId: abfbc9a5-bd31-46a1-afac-90c11ac4390c	Duration: 60063.16 ms	Billed Duration: 60000 ms	Memory Size: 128 MB	Max Memory Used: 16 MB	
```

After (The info log itself has no meaning):
```
// sdk.cfg
...
client-sfn,SFN,states,0
...
```
```
START RequestId: e4f6ca93-e850-4481-9e05-509f77d71540 Version: $LATEST
2024-11-19T13:21:16.333Z	e4f6ca93-e850-4481-9e05-509f77d71540	INFO	[{
    Task Name: 'cjs',
    ops/sec: '15614',
    Average Time (ns): 64043.89050751921,
    Margin: '±187.11%',
    Samples: 2128
  } ]
END RequestId: e4f6ca93-e850-4481-9e05-509f77d71540
REPORT RequestId: e4f6ca93-e850-4481-9e05-509f77d71540	Duration: 508.20 ms	Billed Duration: 568 ms	Memory Size: 128 MB	Max Memory Used: 24 MB	Init Duration: 59.40 ms
```

**Comment by georeeve** [comment]
@nabetti1720 Amazing, thanks for looking into it!
